### ISSUE TITLE
为什么大部分的直播源都不可以使用？

### ISSUE THREAD

**Issue by wilddylan** [billy21/Tvlist-awesome-m3u-m3u8#1]
为什么大部分的直播源都不可以使用？

**Comment by hu-qi** [comment]
很正常 哈哈

**Comment by TDcloud** [comment]
> 为什么大部分的直播源都不可以使用？

你是在哪里使用的尼？

**Comment by billy21** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/87c6054a-9a30-4103-84f4-ade981caf62e-195bd9f4-8692-450c-9eff-a218e51beb4a-v1.png?transparent=1&palette=1&width=246)

国内不同区域观看会受影响，比如部分资源仅针对北京联通IPTV用户观看。

**Comment by TDcloud** [comment]
> > 为什么大部分的直播源都不可以使用？
> 
> 你是在哪里使用的尼？

都可以啊

**Comment by billy21** [comment]
> > > 为什么大部分的直播源都不可以使用？
> > 
> > 
> > 你是在哪里使用的尼？
> 
> 都可以啊

新增多个地方运营商IPTV，可以试试看。

![bitmoji](https://render.bitstrips.com/v2/cpanel/9e82272f-58af-4758-ad2a-690b015247cc-195bd9f4-8692-450c-9eff-a218e51beb4a-v1.png?transparent=1&palette=1&width=246)

**Comment by andyhuai** [comment]
有没有武汉电信的iptv,虽然我宽带有iptv,不想开那个盒子,嘎嘎

**Comment by billy21** [comment]
> 有没有武汉电信的iptv,虽然我宽带有iptv,不想开那个盒子,嘎嘎

武汉电信的IPTV是绑定设备MAC地址的，目前还没有能破的地址，敬请期待。!

[bitmoji](https://render.bitstrips.com/v2/cpanel/d2f18b1d-49db-4e47-837c-bd84b0e1ade9-195bd9f4-8692-450c-9eff-a218e51beb4a-v1.png?transparent=1&palette=1&width=246)

**Comment by andyhuai** [comment]
> > 有没有武汉电信的iptv,虽然我宽带有iptv,不想开那个盒子,嘎嘎
> 
> 武汉电信的IPTV是绑定设备MAC地址的，目前还没有能破的地址，敬请期待。
> 
> ![bitmoji](https://camo.githubusercontent.com/6901ca0b5fc8d8889e19d6c681fc77cb70989c55/68747470733a2f2f72656e6465722e6269747374726970732e636f6d2f76322f6370616e656c2f64326631386231642d343964622d346534372d383337632d6264383462306531616465392d31393562643966342d383639322d343530632d396566662d6132313865353162656234612d76312e706e673f7472616e73706172656e743d312670616c657474653d312677696474683d323436)

感谢,有些源不知道为什么只能播2分钟,然后就卡住了,打开很快

**Comment by billy21** [comment]
> > > 有没有武汉电信的iptv,虽然我宽带有iptv,不想开那个盒子,嘎嘎
> > 
> > 
> > 武汉电信的IPTV是绑定设备MAC地址的，目前还没有能破的地址，敬请期待。
> > ![bitmoji](https://camo.githubusercontent.com/6901ca0b5fc8d8889e19d6c681fc77cb70989c55/68747470733a2f2f72656e6465722e6269747374726970732e636f6d2f76322f6370616e656c2f64326631386231642d343964622d346534372d383337632d6264383462306531616465392d31393562643966342d383639322d343530632d396566662d6132313865353162656234612d76312e706e673f7472616e73706172656e743d312670616c657474653d312677696474683d323436)
> 
> 感谢,有些源不知道为什么只能播2分钟,然后就卡住了,打开很快

不确定，各地的iptv验证方法有不同。估计被服务端踢下线了。

：P

**Comment by sli1989** [comment]
> 有没有武汉电信的iptv,虽然我宽带有iptv,不想开那个盒子,嘎嘎

来一起维护武汉的吧，https://github.com/sli1989/iptv-cn
